---
abstract: 'execute code only once throughout the program''s lifetime'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  Test::Differences: 0
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: once
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=once
  homepage: http://search.cpan.org/dist/once/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/hanekomu/once/tree/master
version: 0.01
